spring:
  datasource:
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: true
    hibernate:
      ddl-auto: update
jwt:
  secret: bjartscularSecretKey
  expiration: 86400000
  refreshExpiration: 86400000
#logging:
#  level:
#    root: ERROR
